language: python
python:
    - "2.7"

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - libboost-all-dev

script:
    - export CXX="clang++-3.7"
    - make
